name: Workflow Test Multi Jobs

on: [push]

concurrency:
  group: test
  cancel-in-progress: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Execute job 1
        run: exit 1 # This will cause the job to fail

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Execute job 2
        run: echo "This is job 2"

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Execute job 3
        run: echo "This is job 3"