name: Workflow Test Matrix

on: [push]

concurrency:
  group: test
  cancel-in-progress: true

jobs:
  job:
    name: Job executed on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            command: exit 1 # This will cause the job to fail
          - os: macos-latest
            command: echo "Running on macos-latest"
          - os: windows-latest
            command: echo "Running on windows-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Execute command
        run: |
          retry=3
          until [ $retry -le 0 ]
          do
            echo "Try #$retry"
            ${{ matrix.command }} && break
            retry=$((retry-1))
            sleep 5
          done
          if [ $retry -le 0 ]; then
            echo "Tests failed after 3 retries."
            exit 1
          fi